name: Trigger auto deployment for fh-test1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fh-test1-AutoDeployTrigger-c21d3c82-1f0a-4270-8b6a-310be1d7ddec.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: fhtestcontainerregistry.azurecr.io
          username: ${{ secrets.FHTEST1_REGISTRY_USERNAME }}
          password: ${{ secrets.FHTEST1_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fhtestcontainerregistry.azurecr.io/fh-test1:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FHTEST1_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n fh-test1 -g rg-fgtest-container-apps --server fhtestcontainerregistry.azurecr.io --username  ${{ secrets.FHTEST1_REGISTRY_USERNAME }} --password ${{ secrets.FHTEST1_REGISTRY_PASSWORD }}
            az containerapp update -n fh-test1 -g rg-fgtest-container-apps --image fhtestcontainerregistry.azurecr.io/fh-test1:${{ github.sha }}
